# Generated by Django 4.0.2 on 2022-02-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrate',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
