# Generated by Django 4.0.2 on 2022-02-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_rating', '0002_alter_projectrate_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='general_rate',
            new_name='total_upvotes',
        ),
        migrations.AddField(
            model_name='projects',
            name='collected_donations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projects',
            name='total_target',
            field=models.IntegerField(default=0),
        ),
    ]
