# Generated by Django 4.0.2 on 2022-02-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_rating', '0010_alter_projects_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProjectRate',
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
